[package]
name = "openvr"
version = "0.2.0"
authors = [
    "Colin Sherratt",
    "Erick Tryzelaar",
    "Rene Eichhorn"
]
build = "src/sys/build.rs"

[lib]
name = "openvr"
path = "src/lib.rs"

[dependencies.openvr_sys]
path = "src/sys/"
